[tool.pumpversion]
current_version = "1.2.0"
commit = false
# tag = true
# tag_name = "v{new_version}"
# message = "Bump version: {current_version} → {new_version}"

[[tool.pumpversion.file]]
path = "src/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[[tool.pumpversion.file]]
path = "app.manifest"
search = 'version="{current_version}.0"'
replace = 'version="{new_version}.0"'

[[tool.pumpversion.file]]
path = "installer.iss"
search = "AppVersion={current_version}"
replace = "AppVersion={new_version}"

[[tool.pumpversion.file]]
path = "installer.iss"
search = "AppVerName=Telegram Auto Download Bot v{current_version}"
replace = "AppVerName=Telegram Auto Download Bot v{new_version}"

[[tool.pumpversion.file]]
path = "installer.iss"
search = "OutputBaseFilename=TelegramAutoDownload-Setup-v{current_version}"
replace = "OutputBaseFilename=TelegramAutoDownload-Setup-v{new_version}"

[[tool.pumpversion.file]]
path = "package_windows.bat"
search = "installer_output\\TelegramAutoDownload-Setup-v{current_version}.exe"
replace = "installer_output\\TelegramAutoDownload-Setup-v{new_version}.exe"

[[tool.pumpversion.file]]
path = "create_version_info.py"
search = "filevers=(1, 2, 0, 0)"
replace = "filevers=({new_version.replace('.', ', ')}, 0)"

[[tool.pumpversion.file]]
path = "create_version_info.py"
search = "StringStruct(u'ProductVersion', u'1.2.0.0')"
replace = "StringStruct(u'ProductVersion', u'{new_version}.0')"

[[tool.pumpversion.file]]
path = "ui.py"
search = 'self.version = "v{current_version}"'
replace = 'self.version = "v{new_version}"'
